<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\DesafioIDez.Aplicacao\DesafioIDez.Aplicacao.csproj" />
    <ProjectReference Include="..\DesafioIDez.Dominio\DesafioIDez.Dominio.csproj" />
  </ItemGroup>

</Project>
